# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Desale Devendra Ramchandra

description: Stylish Jekyll Theme
author:
  name: Desale Devendra
  email: devendra.desale@gmail.com
  github: devendradesale
  twitter: devendradesale
  pinterest: asd123
  linkedin: asd123
  bio: Data scientist
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
